#!/bin/sh

# get commit
hash=`echo $params | sed 's/^.* \(.*\) .*/\1/'`
branch=`git branch --contains $hash`
tail=`git log -1 --pretty=format:' - %H %cn: %s' --abbrev=150 $hash `
last_commit=`echo $branch$tail`

# get last word
info=`echo ${last_commit##* }`

# STDOUT the chapter and question
echo $info
